# -*- coding: utf-8 -*-


X = "x"
Y = "y"
R = "r"  # rotation

XY = (X, Y)
XYR = (X, Y, R)

TIME_TO_UPDATE_SPEED_ML = 5000
MESSAGE_DELAY_SEC = 1
SEND_EVERY_N_TIMER_TIC = 1
CHANGE_SPEED_PER_UPDATE = dict()
DIMENSION = 2

CHANGE_SPEED_PER_UPDATE[X] = 2
CHANGE_SPEED_PER_UPDATE[Y] = 2
CHANGE_SPEED_PER_UPDATE[R] = 20

MAX_SPEED = dict()
MIN_SPEED = dict()

MAX_SPEED[X] = 15
MAX_SPEED[Y] = 15
MAX_SPEED[R] = 10

MIN_SPEED[X] = -15
MIN_SPEED[Y] = -15
MIN_SPEED[R] = -10

MIN_VAL_GEN_POS = dict()
MAX_VAL_GEN_POS = dict()

MAX_VAL_GEN_POS[X] = 30
MAX_VAL_GEN_POS[Y] = 30

MIN_VAL_GEN_POS[X] = -30
MIN_VAL_GEN_POS[Y] = -30

JSON_FILENAME = "state.json"
SAVE_STATE = "save state"
LOAD_STATE = "load state"
